# Generated by Django 4.2 on 2025-02-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=3)),
                ('price_for_medium', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_for_large', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_for_oversized', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('costumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_list', models.CharField(max_length=200, verbose_name='Lista do código de cada categoria de pizza')),
                ('sizes_list', models.CharField(max_length=100, verbose_name='Lista do código de cada tamanho de pizza')),
                ('order_bill', models.DecimalField(decimal_places=2, max_digits=7)),
                ('client_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.costumer')),
            ],
        ),
    ]
